"""Manually curated + verified seed set. Global spread. Quality over quantity.
Costs are international-student estimates in USD/yr. Every data point carries a
status (Verified/Estimated) and a source. Requirements min_gpa on a 4.0 scale."""
from db import db

IMAGES = [
    "https://images.unsplash.com/photo-1575688588571-966e9b61f0b7?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "https://images.unsplash.com/photo-1633987027569-a6599b632de7?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "https://images.unsplash.com/photo-1784308992921-045da5443625?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "https://images.unsplash.com/photo-1763615834709-cd4b196980db?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
]


def vf(value, status="Verified", source=None):
    return {"value": value, "status": status, "source": source, "note": None}


def prog(pid, name, degree, field, dur, tuition, living, deadline, min_gpa, ielts, toefl,
         intake, sch, lang="English", tstat="Verified", src="University official site"):
    return {
        "id": pid, "name": name, "degree": degree, "field": field, "duration_years": dur,
        "language": lang,
        "tuition_per_year": vf(tuition, tstat, src),
        "living_cost_per_year": vf(living, "Estimated", "Numbeo cost-of-living estimate"),
        "intake": intake,
        "application_deadline": vf(deadline, "Verified", src),
        "requirements": {
            "min_gpa": vf(min_gpa, "Verified", src) if min_gpa is not None else None,
            "ielts": vf(ielts, "Verified", src) if ielts is not None else None,
            "toefl": vf(toefl, "Verified", src) if toefl is not None else None,
            "other": None,
        },
        "scholarship_ids": sch,
    }


UNIVERSITIES = [
    {"slug": "mit", "name": "Massachusetts Institute of Technology", "country": "United States",
     "city": "Cambridge, MA", "type": "Private", "qs_ranking": 1, "the_ranking": 2,
     "acceptance_rate": 4.0, "website": "https://mit.edu",
     "description": "World-leading institute for science, engineering and technology.",
     "programs": [
         prog("mit-bsc-cs", "B.Sc. Computer Science & Engineering", "Bachelor", "Computer Science", 4,
              59750, 22000, "2026-01-01", 3.9, 7.0, 100, ["September"], ["mit-need"]),
         prog("mit-msc-cs", "M.Sc. Electrical Engineering & CS", "Master", "Computer Science", 2,
              61990, 24000, "2025-12-15", 3.8, 7.0, 100, ["September"], ["mit-need"]),
     ]},
    {"slug": "stanford", "name": "Stanford University", "country": "United States",
     "city": "Stanford, CA", "type": "Private", "qs_ranking": 6, "the_ranking": 6,
     "acceptance_rate": 4.0, "website": "https://stanford.edu",
     "description": "Elite private research university in Silicon Valley.",
     "programs": [
         prog("stan-bsc-ds", "B.Sc. Data Science", "Bachelor", "Data Science", 4,
              62000, 25000, "2026-01-05", 3.9, 7.0, 100, ["September"], ["stan-knight"]),
         prog("stan-mba", "MBA", "Master", "Business", 2,
              82000, 30000, "2026-04-09", 3.6, 7.0, 100, ["September"], []),
     ]},
    {"slug": "harvard", "name": "Harvard University", "country": "United States",
     "city": "Cambridge, MA", "type": "Private", "qs_ranking": 4, "the_ranking": 3,
     "acceptance_rate": 3.4, "website": "https://harvard.edu",
     "description": "The oldest and among the most prestigious US universities.",
     "programs": [
         prog("harv-bsc-econ", "A.B. Economics", "Bachelor", "Economics", 4,
              57000, 24000, "2026-01-01", 3.9, 7.5, 100, ["September"], ["harv-need"]),
         prog("harv-msc-law", "Master of Laws (LL.M.)", "Master", "Law", 1,
              75000, 26000, "2025-12-01", 3.7, 7.0, 100, ["September"], []),
     ]},
    {"slug": "oxford", "name": "University of Oxford", "country": "United Kingdom",
     "city": "Oxford", "type": "Public", "qs_ranking": 3, "the_ranking": 1,
     "acceptance_rate": 17.0, "website": "https://ox.ac.uk",
     "description": "The oldest university in the English-speaking world.",
     "programs": [
         prog("ox-bsc-ppe", "BA Philosophy, Politics & Economics", "Bachelor", "Economics", 3,
              44000, 18000, "2025-10-15", 3.8, 7.0, 110, ["October"], ["ox-reach"]),
         prog("ox-msc-cs", "MSc Computer Science", "Master", "Computer Science", 1,
              51000, 19000, "2026-01-20", 3.7, 7.5, 110, ["October"], ["ox-clarendon"]),
     ]},
    {"slug": "cambridge", "name": "University of Cambridge", "country": "United Kingdom",
     "city": "Cambridge", "type": "Public", "qs_ranking": 5, "the_ranking": 5,
     "acceptance_rate": 21.0, "website": "https://cam.ac.uk",
     "description": "Historic collegiate research university in England.",
     "programs": [
         prog("cam-beng", "BA/MEng Engineering", "Bachelor", "Engineering", 4,
              43000, 17000, "2025-10-15", 3.8, 7.5, 110, ["October"], ["cam-gates"]),
         prog("cam-msc-fin", "MPhil Finance", "Master", "Business", 1,
              52000, 18000, "2026-01-10", 3.7, 7.5, 100, ["October"], []),
     ]},
    {"slug": "imperial", "name": "Imperial College London", "country": "United Kingdom",
     "city": "London", "type": "Public", "qs_ranking": 2, "the_ranking": 9,
     "acceptance_rate": 14.0, "website": "https://imperial.ac.uk",
     "description": "Science, engineering, medicine and business specialist.",
     "programs": [
         prog("imp-bsc-cs", "BEng Computing", "Bachelor", "Computer Science", 3,
              48000, 20000, "2026-01-29", 3.7, 7.0, 100, ["October"], []),
         prog("imp-msc-ds", "MSc Machine Learning", "Master", "Data Science", 1,
              45000, 21000, "2026-03-31", 3.6, 7.0, 100, ["October"], []),
     ]},
    {"slug": "ucl", "name": "University College London", "country": "United Kingdom",
     "city": "London", "type": "Public", "qs_ranking": 9, "the_ranking": 22,
     "acceptance_rate": 30.0, "website": "https://ucl.ac.uk",
     "description": "Large multidisciplinary university in central London.",
     "programs": [
         prog("ucl-bsc-psy", "BSc Psychology", "Bachelor", "Psychology", 3,
              38000, 20000, "2026-01-29", 3.5, 6.5, 92, ["September"], []),
         prog("ucl-msc-ux", "MSc Human-Computer Interaction", "Master", "Design", 1,
              40000, 20000, "2026-03-30", 3.4, 6.5, 96, ["September"], []),
     ]},
    {"slug": "toronto", "name": "University of Toronto", "country": "Canada",
     "city": "Toronto", "type": "Public", "qs_ranking": 25, "the_ranking": 21,
     "acceptance_rate": 43.0, "website": "https://utoronto.ca",
     "description": "Canada's leading research university.",
     "programs": [
         prog("uoft-bsc-cs", "HBSc Computer Science", "Bachelor", "Computer Science", 4,
              45000, 15000, "2026-01-15", 3.6, 6.5, 100, ["September"], ["uoft-lester"]),
         prog("uoft-msc-ds", "MSc Applied Computing", "Master", "Data Science", 1.5,
              42000, 16000, "2025-12-01", 3.5, 7.0, 100, ["September"], []),
     ]},
    {"slug": "ubc", "name": "University of British Columbia", "country": "Canada",
     "city": "Vancouver", "type": "Public", "qs_ranking": 38, "the_ranking": 41,
     "acceptance_rate": 52.0, "website": "https://ubc.ca",
     "description": "Coastal Canadian research university with strong sciences.",
     "programs": [
         prog("ubc-bsc-env", "BSc Environmental Sciences", "Bachelor", "Environmental Science", 4,
              41000, 15000, "2026-01-15", 3.4, 6.5, 90, ["September"], ["ubc-ies"]),
         prog("ubc-beng", "BASc Engineering", "Bachelor", "Engineering", 4,
              44000, 15000, "2026-01-15", 3.5, 6.5, 90, ["September"], ["ubc-ies"]),
     ]},
    {"slug": "mcgill", "name": "McGill University", "country": "Canada",
     "city": "Montreal", "type": "Public", "qs_ranking": 29, "the_ranking": 45,
     "acceptance_rate": 46.0, "website": "https://mcgill.ca",
     "description": "Historic English-language university in Quebec.",
     "programs": [
         prog("mcg-bcom", "B.Com. Management", "Bachelor", "Business", 3,
              38000, 14000, "2026-01-15", 3.5, 6.5, 90, ["September"], []),
         prog("mcg-msc-cs", "MSc Computer Science", "Master", "Computer Science", 2,
              22000, 14000, "2025-12-15", 3.4, 6.5, 86, ["September"], []),
     ]},
    {"slug": "eth-zurich", "name": "ETH Zurich", "country": "Switzerland",
     "city": "Zurich", "type": "Public", "qs_ranking": 7, "the_ranking": 11,
     "acceptance_rate": 27.0, "website": "https://ethz.ch",
     "description": "Europe's top technical university, very low tuition.",
     "programs": [
         prog("eth-bsc-cs", "BSc Computer Science", "Bachelor", "Computer Science", 3,
              1600, 22000, "2026-04-30", 3.7, 7.0, 100, ["September"], ["eth-excellence"], lang="German"),
         prog("eth-msc-ds", "MSc Data Science", "Master", "Data Science", 2,
              1600, 22000, "2025-12-15", 3.6, 7.0, 100, ["September"], ["eth-excellence"]),
     ]},
    {"slug": "tum", "name": "Technical University of Munich", "country": "Germany",
     "city": "Munich", "type": "Public", "qs_ranking": 28, "the_ranking": 26,
     "acceptance_rate": 8.0, "website": "https://tum.de",
     "description": "Germany's premier technical university; near-free tuition.",
     "programs": [
         prog("tum-bsc-eng", "BSc Mechanical Engineering", "Bachelor", "Engineering", 3,
              300, 12000, "2026-01-15", 3.3, 6.5, 88, ["October"], ["daad-epos"], lang="German"),
         prog("tum-msc-cs", "MSc Informatics", "Master", "Computer Science", 2,
              300, 12000, "2026-05-31", 3.3, 6.5, 88, ["October"], ["daad-epos"]),
     ]},
    {"slug": "lmu-munich", "name": "Ludwig Maximilian University of Munich", "country": "Germany",
     "city": "Munich", "type": "Public", "qs_ranking": 59, "the_ranking": 38,
     "acceptance_rate": 12.0, "website": "https://lmu.de",
     "description": "One of Europe's oldest and most respected universities.",
     "programs": [
         prog("lmu-bsc-econ", "BSc Economics", "Bachelor", "Economics", 3,
              300, 12000, "2026-07-15", 3.2, 6.5, 88, ["October"], ["daad-epos"], lang="German"),
         prog("lmu-msc-psy", "MSc Psychology", "Master", "Psychology", 2,
              300, 12000, "2026-05-31", 3.4, 6.5, 88, ["October"], []),
     ]},
    {"slug": "tu-delft", "name": "Delft University of Technology", "country": "Netherlands",
     "city": "Delft", "type": "Public", "qs_ranking": 49, "the_ranking": 48,
     "acceptance_rate": 35.0, "website": "https://tudelft.nl",
     "description": "Top European engineering and design university.",
     "programs": [
         prog("delft-bsc-eng", "BSc Aerospace Engineering", "Bachelor", "Engineering", 3,
              18000, 14000, "2026-01-15", 3.4, 6.5, 90, ["September"], ["nl-orange"]),
         prog("delft-msc-design", "MSc Industrial Design Engineering", "Master", "Design", 2,
              19000, 14000, "2026-04-01", 3.3, 6.5, 90, ["September"], ["nl-orange"]),
     ]},
    {"slug": "amsterdam", "name": "University of Amsterdam", "country": "Netherlands",
     "city": "Amsterdam", "type": "Public", "qs_ranking": 53, "the_ranking": 61,
     "acceptance_rate": 40.0, "website": "https://uva.nl",
     "description": "Broad research university in the heart of Amsterdam.",
     "programs": [
         prog("uva-bsc-ds", "BSc Data Science & AI", "Bachelor", "Data Science", 3,
              16000, 15000, "2026-01-15", 3.3, 6.5, 92, ["September"], ["nl-orange"]),
         prog("uva-msc-econ", "MSc Economics", "Master", "Economics", 1,
              17000, 15000, "2026-04-01", 3.3, 6.5, 92, ["September"], []),
     ]},
    {"slug": "ku-leuven", "name": "KU Leuven", "country": "Belgium",
     "city": "Leuven", "type": "Public", "qs_ranking": 61, "the_ranking": 45,
     "acceptance_rate": 44.0, "website": "https://kuleuven.be",
     "description": "Belgium's highest-ranked and oldest Catholic university.",
     "programs": [
         prog("kul-msc-ai", "MSc Artificial Intelligence", "Master", "Computer Science", 1,
              7000, 12000, "2026-03-01", 3.4, 6.5, 90, ["September"], []),
         prog("kul-bsc-bio", "BSc Bioscience Engineering", "Bachelor", "Environmental Science", 3,
              4000, 12000, "2026-06-01", 3.2, 6.5, 90, ["September"], []),
     ]},
    {"slug": "sorbonne", "name": "Sorbonne University", "country": "France",
     "city": "Paris", "type": "Public", "qs_ranking": 59, "the_ranking": 75,
     "acceptance_rate": 30.0, "website": "https://sorbonne-universite.fr",
     "description": "Renowned Parisian university for sciences and humanities.",
     "programs": [
         prog("sorb-bsc-math", "BSc Mathematics", "Bachelor", "Data Science", 3,
              3000, 16000, "2026-03-15", 3.3, 6.0, 80, ["September"], ["eiffel"], lang="French"),
         prog("sorb-msc-cs", "MSc Computer Science", "Master", "Computer Science", 2,
              4000, 16000, "2026-01-31", 3.4, 6.5, 85, ["September"], ["eiffel"]),
     ]},
    {"slug": "psl", "name": "PSL University", "country": "France",
     "city": "Paris", "type": "Public", "qs_ranking": 24, "the_ranking": 43,
     "acceptance_rate": 22.0, "website": "https://psl.eu",
     "description": "Elite Paris research collegiate university.",
     "programs": [
         prog("psl-msc-econ", "MSc Economics", "Master", "Economics", 2,
              5000, 17000, "2026-02-15", 3.5, 6.5, 90, ["September"], ["eiffel"]),
     ]},
    {"slug": "kth", "name": "KTH Royal Institute of Technology", "country": "Sweden",
     "city": "Stockholm", "type": "Public", "qs_ranking": 73, "the_ranking": 89,
     "acceptance_rate": 34.0, "website": "https://kth.se",
     "description": "Sweden's largest technical university.",
     "programs": [
         prog("kth-msc-cs", "MSc Computer Science", "Master", "Computer Science", 2,
              16000, 13000, "2026-01-15", 3.4, 6.5, 90, ["September"], ["si-scholarship"]),
         prog("kth-msc-env", "MSc Environmental Engineering", "Master", "Environmental Science", 2,
              16000, 13000, "2026-01-15", 3.3, 6.5, 90, ["September"], ["si-scholarship"]),
     ]},
    {"slug": "lund", "name": "Lund University", "country": "Sweden",
     "city": "Lund", "type": "Public", "qs_ranking": 75, "the_ranking": 106,
     "acceptance_rate": 40.0, "website": "https://lu.se",
     "description": "One of Scandinavia's oldest and broadest universities.",
     "programs": [
         prog("lund-bsc-econ", "BSc International Business", "Bachelor", "Business", 3,
              12000, 12000, "2026-01-15", 3.2, 6.5, 90, ["September"], ["si-scholarship"]),
     ]},
    {"slug": "copenhagen", "name": "University of Copenhagen", "country": "Denmark",
     "city": "Copenhagen", "type": "Public", "qs_ranking": 82, "the_ranking": 107,
     "acceptance_rate": 41.0, "website": "https://ku.dk",
     "description": "Denmark's oldest and largest research university.",
     "programs": [
         prog("kbh-msc-bio", "MSc Biology", "Master", "Environmental Science", 2,
              16000, 15000, "2026-01-15", 3.3, 6.5, 88, ["September"], []),
     ]},
    {"slug": "helsinki", "name": "University of Helsinki", "country": "Finland",
     "city": "Helsinki", "type": "Public", "qs_ranking": 115, "the_ranking": 101,
     "acceptance_rate": 45.0, "website": "https://helsinki.fi",
     "description": "Finland's leading multidisciplinary university.",
     "programs": [
         prog("hel-msc-ds", "MSc Data Science", "Master", "Data Science", 2,
              15000, 12000, "2026-01-10", 3.2, 6.5, 92, ["September"], []),
     ]},
    {"slug": "nus", "name": "National University of Singapore", "country": "Singapore",
     "city": "Singapore", "type": "Public", "qs_ranking": 8, "the_ranking": 17,
     "acceptance_rate": 12.0, "website": "https://nus.edu.sg",
     "description": "Asia's top-ranked comprehensive research university.",
     "programs": [
         prog("nus-bsc-cs", "BComp Computer Science", "Bachelor", "Computer Science", 4,
              29000, 14000, "2026-02-28", 3.6, 6.5, 92, ["August"], ["nus-global"]),
         prog("nus-mba", "MBA", "Master", "Business", 1.5,
              47000, 16000, "2026-01-31", 3.5, 7.0, 100, ["August"], []),
     ]},
    {"slug": "ntu-sg", "name": "Nanyang Technological University", "country": "Singapore",
     "city": "Singapore", "type": "Public", "qs_ranking": 15, "the_ranking": 30,
     "acceptance_rate": 25.0, "website": "https://ntu.edu.sg",
     "description": "Young, fast-rising Singaporean science & tech university.",
     "programs": [
         prog("ntu-beng", "BEng Electrical & Electronic", "Bachelor", "Engineering", 4,
              26000, 14000, "2026-02-28", 3.5, 6.0, 90, ["August"], []),
         prog("ntu-msc-ai", "MSc Artificial Intelligence", "Master", "Computer Science", 1,
              38000, 15000, "2026-03-31", 3.5, 6.5, 92, ["August"], []),
     ]},
    {"slug": "hku", "name": "University of Hong Kong", "country": "Hong Kong",
     "city": "Hong Kong", "type": "Public", "qs_ranking": 17, "the_ranking": 35,
     "acceptance_rate": 20.0, "website": "https://hku.hk",
     "description": "Hong Kong's oldest and most international university.",
     "programs": [
         prog("hku-bba", "BBA International Business", "Bachelor", "Business", 4,
              22000, 16000, "2026-01-15", 3.5, 6.5, 93, ["September"], ["hku-entrance"]),
         prog("hku-msc-fin", "MSc Finance", "Master", "Business", 1,
              48000, 18000, "2025-12-31", 3.5, 7.0, 100, ["September"], []),
     ]},
    {"slug": "tokyo", "name": "University of Tokyo", "country": "Japan",
     "city": "Tokyo", "type": "Public", "qs_ranking": 32, "the_ranking": 28,
     "acceptance_rate": 34.0, "website": "https://u-tokyo.ac.jp",
     "description": "Japan's most prestigious national university.",
     "programs": [
         prog("todai-bsc-eng", "BSc Engineering (PEAK, English)", "Bachelor", "Engineering", 4,
              5000, 15000, "2025-12-01", 3.5, 7.0, 100, ["September"], ["mext"]),
         prog("todai-msc-cs", "MSc Information Science", "Master", "Computer Science", 2,
              5000, 15000, "2025-12-01", 3.4, 7.0, 95, ["September"], ["mext"]),
     ]},
    {"slug": "kaist", "name": "KAIST", "country": "South Korea",
     "city": "Daejeon", "type": "Public", "qs_ranking": 53, "the_ranking": 82,
     "acceptance_rate": 15.0, "website": "https://kaist.ac.kr",
     "description": "Korea's flagship science and technology institute.",
     "programs": [
         prog("kaist-bsc-cs", "BSc Computer Science", "Bachelor", "Computer Science", 4,
              8000, 12000, "2026-04-30", 3.5, 6.5, 83, ["September"], ["kaist-scholar"]),
     ]},
    {"slug": "tsinghua", "name": "Tsinghua University", "country": "China",
     "city": "Beijing", "type": "Public", "qs_ranking": 20, "the_ranking": 12,
     "acceptance_rate": 15.0, "website": "https://tsinghua.edu.cn",
     "description": "China's top-ranked university for engineering & tech.",
     "programs": [
         prog("tsinghua-msc-econ", "Master of Economics (Global)", "Master", "Economics", 2,
              9000, 10000, "2026-03-15", 3.5, 6.5, 90, ["September"], ["csc-china"]),
     ]},
    {"slug": "melbourne", "name": "University of Melbourne", "country": "Australia",
     "city": "Melbourne", "type": "Public", "qs_ranking": 13, "the_ranking": 39,
     "acceptance_rate": 70.0, "website": "https://unimelb.edu.au",
     "description": "Australia's leading research university.",
     "programs": [
         prog("melb-bsc", "Bachelor of Science", "Bachelor", "Data Science", 3,
              33000, 18000, "2025-10-31", 3.3, 6.5, 79, ["February"], ["melb-intl"]),
         prog("melb-msc-eng", "Master of Engineering", "Master", "Engineering", 2,
              35000, 18000, "2025-10-31", 3.3, 6.5, 79, ["February"], []),
     ]},
    {"slug": "unsw", "name": "University of New South Wales", "country": "Australia",
     "city": "Sydney", "type": "Public", "qs_ranking": 19, "the_ranking": 71,
     "acceptance_rate": 65.0, "website": "https://unsw.edu.au",
     "description": "Sydney research university strong in engineering & business.",
     "programs": [
         prog("unsw-bcom", "Bachelor of Commerce", "Bachelor", "Business", 3,
              32000, 19000, "2026-01-31", 3.2, 6.5, 90, ["February"], []),
         prog("unsw-msc-ds", "Master of Data Science", "Master", "Data Science", 2,
              34000, 19000, "2026-01-31", 3.3, 6.5, 90, ["February"], []),
     ]},
    {"slug": "auckland", "name": "University of Auckland", "country": "New Zealand",
     "city": "Auckland", "type": "Public", "qs_ranking": 65, "the_ranking": 152,
     "acceptance_rate": 55.0, "website": "https://auckland.ac.nz",
     "description": "New Zealand's highest-ranked university.",
     "programs": [
         prog("auck-bsc-env", "BSc Environmental Science", "Bachelor", "Environmental Science", 3,
              27000, 15000, "2025-12-08", 3.2, 6.0, 80, ["March"], []),
     ]},
    {"slug": "trinity-dublin", "name": "Trinity College Dublin", "country": "Ireland",
     "city": "Dublin", "type": "Public", "qs_ranking": 87, "the_ranking": 81,
     "acceptance_rate": 33.0, "website": "https://tcd.ie",
     "description": "Ireland's oldest and most prestigious university.",
     "programs": [
         prog("tcd-bsc-cs", "BA Computer Science", "Bachelor", "Computer Science", 4,
              29000, 16000, "2026-02-01", 3.4, 6.5, 90, ["September"], []),
     ]},
]

SCHOLARSHIPS = [
    {"slug": "mit-need", "name": "MIT Need-Based Aid", "provider": "Massachusetts Institute of Technology",
     "university_slug": "mit", "coverage_type": "Full", "coverage_text": "Full demonstrated need met",
     "amount_per_year": None, "degree_level": "Bachelor", "field": "Any",
     "eligibility": {"need_based": True, "min_gpa": 3.7},
     "deadline": vf("2026-02-15", "Verified", "MIT Student Financial Services"),
     "requirements_text": "Need assessed via CSS Profile; no separate merit application.",
     "link": "https://sfs.mit.edu"},
    {"slug": "stan-knight", "name": "Knight-Hennessy Scholars", "provider": "Stanford University",
     "university_slug": "stanford", "coverage_type": "Full", "coverage_text": "Full tuition + stipend",
     "amount_per_year": 90000, "degree_level": "Master", "field": "Any",
     "eligibility": {"merit_based": True, "min_gpa": 3.7, "min_ielts": 7.0},
     "deadline": vf("2025-10-08", "Verified", "Knight-Hennessy official"),
     "requirements_text": "Leadership essays, references, graduate program admission.",
     "link": "https://knight-hennessy.stanford.edu"},
    {"slug": "harv-need", "name": "Harvard Financial Aid Initiative", "provider": "Harvard University",
     "university_slug": "harvard", "coverage_type": "Full", "coverage_text": "Full need-based grant",
     "amount_per_year": None, "degree_level": "Bachelor", "field": "Any",
     "eligibility": {"need_based": True, "min_gpa": 3.8},
     "deadline": vf("2026-02-01", "Verified", "Harvard Griffin Financial Aid"),
     "requirements_text": "CSS Profile + family income documentation.",
     "link": "https://college.harvard.edu/financial-aid"},
    {"slug": "ox-clarendon", "name": "Clarendon Fund Scholarship", "provider": "University of Oxford",
     "university_slug": "oxford", "coverage_type": "Full", "coverage_text": "Full fees + living stipend",
     "amount_per_year": 40000, "degree_level": "Master", "field": "Any",
     "eligibility": {"merit_based": True, "min_gpa": 3.7, "min_ielts": 7.5},
     "deadline": vf("2026-01-20", "Verified", "Oxford Clarendon Fund"),
     "requirements_text": "Automatic consideration on graduate application.",
     "link": "https://ox.ac.uk/clarendon"},
    {"slug": "ox-reach", "name": "Reach Oxford Scholarship", "provider": "University of Oxford",
     "university_slug": "oxford", "coverage_type": "Full", "coverage_text": "Fees, living, one return flight",
     "amount_per_year": 35000, "degree_level": "Bachelor", "field": "Any",
     "eligibility": {"need_based": True, "min_gpa": 3.6, "min_ielts": 7.0},
     "deadline": vf("2025-10-15", "Verified", "Oxford UG funding"),
     "requirements_text": "For students from low-income countries unable to fund study.",
     "link": "https://ox.ac.uk/reach"},
    {"slug": "cam-gates", "name": "Gates Cambridge Scholarship", "provider": "University of Cambridge",
     "university_slug": "cambridge", "coverage_type": "Full", "coverage_text": "Full cost of study + stipend",
     "amount_per_year": 45000, "degree_level": "Master", "field": "Any",
     "eligibility": {"merit_based": True, "min_gpa": 3.8, "min_ielts": 7.5},
     "deadline": vf("2025-12-03", "Verified", "Gates Cambridge Trust"),
     "requirements_text": "Outstanding academic record + leadership + apply with admission.",
     "link": "https://gatescambridge.org"},
    {"slug": "uoft-lester", "name": "Lester B. Pearson Scholarship", "provider": "University of Toronto",
     "university_slug": "toronto", "coverage_type": "Full", "coverage_text": "Tuition, books, incidental fees, residence",
     "amount_per_year": 55000, "degree_level": "Bachelor", "field": "Any",
     "eligibility": {"merit_based": True, "min_gpa": 3.8, "min_ielts": 6.5},
     "deadline": vf("2025-11-30", "Verified", "U of T Pearson"),
     "requirements_text": "School nomination required; exceptional achievement.",
     "link": "https://future.utoronto.ca/pearson"},
    {"slug": "ubc-ies", "name": "UBC International Scholars Award", "provider": "University of British Columbia",
     "university_slug": "ubc", "coverage_type": "Partial", "coverage_text": "Partial to full tuition support",
     "amount_per_year": 25000, "degree_level": "Bachelor", "field": "Any",
     "eligibility": {"need_based": True, "merit_based": True, "min_gpa": 3.5, "min_ielts": 6.5},
     "deadline": vf("2025-12-01", "Verified", "UBC International"),
     "requirements_text": "Financial need + strong academics + community engagement.",
     "link": "https://you.ubc.ca/financial-planning/scholarships-awards-international-students"},
    {"slug": "eth-excellence", "name": "ETH Excellence Scholarship (ESOP)", "provider": "ETH Zurich",
     "university_slug": "eth-zurich", "coverage_type": "Full", "coverage_text": "Living stipend + tuition waiver",
     "amount_per_year": 32000, "degree_level": "Master", "field": "Any",
     "eligibility": {"merit_based": True, "min_gpa": 3.7, "min_ielts": 7.0},
     "deadline": vf("2025-12-15", "Verified", "ETH Zurich ESOP"),
     "requirements_text": "Top 10% of cohort; apply with Master's application.",
     "link": "https://ethz.ch/esop"},
    {"slug": "daad-epos", "name": "DAAD Development-Related Scholarship", "provider": "DAAD (Germany)",
     "university_slug": None, "country": "Germany", "coverage_type": "Full", "coverage_text": "Monthly stipend + tuition + travel",
     "amount_per_year": 15000, "degree_level": "Master", "field": "Any",
     "eligibility": {"need_based": True, "min_gpa": 3.3, "min_ielts": 6.5},
     "deadline": vf("2026-03-31", "Estimated", "DAAD (varies by program)"),
     "requirements_text": "Two years work experience often required; for developing countries.",
     "link": "https://daad.de"},
    {"slug": "nl-orange", "name": "Orange Tulip Scholarship", "provider": "Nuffic (Netherlands)",
     "university_slug": None, "country": "Netherlands", "coverage_type": "Partial", "coverage_text": "Partial tuition reduction",
     "amount_per_year": 10000, "degree_level": "Any", "field": "Any",
     "eligibility": {"merit_based": True, "min_gpa": 3.3, "min_ielts": 6.5},
     "deadline": vf("2026-04-01", "Estimated", "Nuffic Neso"),
     "requirements_text": "Country-specific; admission to a Dutch institution required.",
     "link": "https://studyinnl.org"},
    {"slug": "eiffel", "name": "Eiffel Excellence Scholarship", "provider": "Campus France",
     "university_slug": None, "country": "France", "coverage_type": "Stipend", "coverage_text": "Monthly stipend + travel + insurance",
     "amount_per_year": 16000, "degree_level": "Master", "field": "Any",
     "eligibility": {"merit_based": True, "min_gpa": 3.5},
     "deadline": vf("2026-01-10", "Verified", "Campus France Eiffel"),
     "requirements_text": "Institution nominates candidate; strong academic profile.",
     "link": "https://campusfrance.org/en/eiffel-scholarship-program-of-excellence"},
    {"slug": "si-scholarship", "name": "Swedish Institute Scholarship (SISGP)", "provider": "Swedish Institute",
     "university_slug": None, "country": "Sweden", "coverage_type": "Full", "coverage_text": "Tuition + living + insurance + travel",
     "amount_per_year": 20000, "degree_level": "Master", "field": "Any",
     "eligibility": {"merit_based": True, "need_based": True, "min_gpa": 3.4, "min_ielts": 6.5},
     "deadline": vf("2026-02-11", "Verified", "Swedish Institute"),
     "requirements_text": "Leadership + work experience; eligible country list.",
     "link": "https://si.se"},
    {"slug": "nus-global", "name": "NUS Global Merit Scholarship", "provider": "National University of Singapore",
     "university_slug": "nus", "coverage_type": "Partial", "coverage_text": "Tuition + annual living allowance",
     "amount_per_year": 18000, "degree_level": "Bachelor", "field": "Any",
     "eligibility": {"merit_based": True, "min_gpa": 3.6, "min_ielts": 6.5},
     "deadline": vf("2026-02-28", "Verified", "NUS Admissions"),
     "requirements_text": "Outstanding academics; considered at admission.",
     "link": "https://nus.edu.sg/oam/scholarships"},
    {"slug": "hku-entrance", "name": "HKU Foundation Entrance Scholarship", "provider": "University of Hong Kong",
     "university_slug": "hku", "coverage_type": "Partial", "coverage_text": "Partial to full tuition",
     "amount_per_year": 20000, "degree_level": "Bachelor", "field": "Any",
     "eligibility": {"merit_based": True, "min_gpa": 3.5, "min_ielts": 6.5},
     "deadline": vf("2026-01-15", "Verified", "HKU Scholarships"),
     "requirements_text": "Automatic consideration for top admitted students.",
     "link": "https://aal.hku.hk/admissions/international/scholarships"},
    {"slug": "mext", "name": "MEXT Japanese Government Scholarship", "provider": "Government of Japan",
     "university_slug": None, "country": "Japan", "coverage_type": "Full", "coverage_text": "Tuition + monthly stipend + travel",
     "amount_per_year": 14000, "degree_level": "Any", "field": "Any",
     "eligibility": {"merit_based": True, "min_gpa": 3.4},
     "deadline": vf("2025-12-01", "Estimated", "Japanese embassy (varies)"),
     "requirements_text": "Embassy or university recommendation track.",
     "link": "https://studyinjapan.go.jp"},
    {"slug": "csc-china", "name": "Chinese Government Scholarship (CSC)", "provider": "China Scholarship Council",
     "university_slug": None, "country": "China", "coverage_type": "Full", "coverage_text": "Tuition + accommodation + stipend",
     "amount_per_year": 12000, "degree_level": "Any", "field": "Any",
     "eligibility": {"merit_based": True, "min_gpa": 3.3},
     "deadline": vf("2026-03-15", "Estimated", "CSC (varies by university)"),
     "requirements_text": "Apply via university or Chinese embassy.",
     "link": "https://campuschina.org"},
    {"slug": "kaist-scholar", "name": "KAIST International Scholarship", "provider": "KAIST",
     "university_slug": "kaist", "coverage_type": "Full", "coverage_text": "Full tuition + living stipend",
     "amount_per_year": 12000, "degree_level": "Bachelor", "field": "Computer Science",
     "eligibility": {"merit_based": True, "min_gpa": 3.5, "min_ielts": 6.5},
     "deadline": vf("2026-04-30", "Verified", "KAIST Admissions"),
     "requirements_text": "Strong STEM record; maintained by GPA condition.",
     "link": "https://admission.kaist.ac.kr"},
    {"slug": "melb-intl", "name": "Melbourne International Undergraduate Scholarship", "provider": "University of Melbourne",
     "university_slug": "melbourne", "coverage_type": "Partial", "coverage_text": "10k–full tuition remission",
     "amount_per_year": 12000, "degree_level": "Bachelor", "field": "Any",
     "eligibility": {"merit_based": True, "min_gpa": 3.4, "min_ielts": 6.5},
     "deadline": vf("2025-10-31", "Verified", "Melbourne Scholarships"),
     "requirements_text": "Automatic; based on academic merit at admission.",
     "link": "https://study.unimelb.edu.au/how-to-apply/scholarships"},
]


async def seed_data():
    for u in UNIVERSITIES:
        await db.universities.update_one({"slug": u["slug"]}, {"$set": u}, upsert=True)
    # assign images deterministically
    for i, u in enumerate(UNIVERSITIES):
        await db.universities.update_one({"slug": u["slug"]},
                                         {"$set": {"image_url": IMAGES[i % len(IMAGES)]}})
    for s in SCHOLARSHIPS:
        await db.scholarships.update_one({"slug": s["slug"]}, {"$set": s}, upsert=True)
